### PR TITLE
Add method metadata to context

### PR DESCRIPTION
**Pull request by alexus1024**
## WHAT
See header

## WHY
Metadata in context allows params unmarshalling as a general step for processing jsonrpc request

### CODE REVIEW

**Comment by alexus1024** [comment]
By the way - intent to have all Metadata object in context is questionable. It contains Handler, and when a handler have this link to handler - it`s like a mess. Maybe.
Actually, I currently need params only, result - in perspective.
What`s your opinion on that?

**Comment by alexus1024** [comment]
By the way, why you make the http.Request object inaccessible at the jsontpc.Handler?
Is there some reason for it?

**Comment by osamingo** [comment]
@alexus1024 

Sorry for the late code review.
I skim-read it but looks good.
Please resolve the code conflicts.

And If you have a question, please create an issue.

**Comment by alexus1024** [comment]
@alexus1024  

> Please resolve the code conflicts.


what code conflicts are you talking about?
All have been solved more than week ago. Github tells that branch is currently mergable.

I have try`d  to merge it to master locally just now - there was no conflicts too.

**Comment by osamingo** [comment]
@alexus1024 Really? I see a conflict on my display...

image

**Comment by osamingo** [comment]
@alexus1024 Ahhh, sorry. I was not checking to a case of the merge commit.
Please your branch able to rebase commit to the master branch!

**Comment by alexus1024** [comment]
Now I see the problem. I`ll fix it soon, thanks.

**Comment by alexus1024** [comment]
I give up with this PR - can't make it margeable for some technical reason.
It's features has been moved to #42

**Pull request closed without merging**
